GOOGLE_API_KEY = "AIzaSyC7-64QIKhXMuD_uIwX7XkJ-JKD91aeXTY"
LANGCHAIN_TRACING_V2 = "true"
LANGCHAIN_API_KEY = "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"
OPENAI_API_KEY = "sk-B8ev91hHGkyDPNp_SIFmDqYfCUdBFCDio8VQyCPbRbT3BlbkFJ0Lzr-M1dzCY7x3Bj5_YQgpDwFkdWd2-13M5QsgercA"
