GOOGLE_API_KEY = "AIzaSyC7-64QIKhXMuD_uIwX7XkJ-JKD91aeXTY"
LANGCHAIN_TRACING_V2 = "true"
LANGCHAIN_API_KEY = "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"
PINECONE_API_KEY = "ee833543-3aca-4adb-9acd-60ae9c30fca8"
